repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: "v0.0.261"
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "" # Use the sha / tag you want to point at
    hooks:
      - id: eslint
