name: frontend ci

on: [push]

jobs:
  linting:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./frontend"

    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm i

      - name: Code Linting
        run: npm run lint
